# Generated by Django 4.1 on 2022-09-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maquina',
            name='bateria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maquina',
            name='cargador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maquina',
            name='contrasenia',
            field=models.CharField(default='/', max_length=40),
        ),
        migrations.AddField(
            model_name='maquina',
            name='enciende',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maquina',
            name='falla',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='maquina',
            name='faltantes_tornillos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maquina',
            name='formato',
            field=models.CharField(default='/', max_length=40),
        ),
        migrations.AddField(
            model_name='maquina',
            name='marca',
            field=models.CharField(default='/', max_length=40),
        ),
        migrations.AddField(
            model_name='maquina',
            name='modelo',
            field=models.CharField(default='/', max_length=40),
        ),
        migrations.AddField(
            model_name='maquina',
            name='muestra_imagen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maquina',
            name='rayas_roturas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maquina',
            name='sistema',
            field=models.CharField(default='/', max_length=40),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tiene_leds',
            field=models.BooleanField(default=False),
        ),
    ]
