# Generated by Django 4.1 on 2022-09-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0002_maquina_backup_maquina_bateria_maquina_cargador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dni_cuit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='backup',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='bateria',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='cargador',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='enciende',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='faltantes_tornillos',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='muestra_imagen',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='rayas_roturas',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tiene_leds',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
